name: Build PlatformIO project
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build ESP8266 Project
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'
        
      - name: Install Python Dependencies
        run: pip install -r requirements.txt
        
      - name: Cache PlatformIO build cache
        uses: actions/cache@v4
        with:
          path: ~/.platformio/.cache
          key: ${{ runner.os }}-platformio-${{ hashFiles('platformio.ini') }}

      - name: Verify PlatformIO Installation
        run: pio --version

      - name: Build PlatformIO Project
        run: pio run
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: firmware
          path: .pio/build/nodemcuv2/firmware.*
          retention-days: 7