---
name: Super-Linter Light

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  super-linter:
    name: Lint Code Base
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Super-Linter
        uses: super-linter/super-linter/slim@v5
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_CPP: true
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
          VALIDATE_JSON: true
          SUPPRESS_POSSUM: true
